// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveAll() {
  return window['go']['main']['App']['ApproveAll']();
}

export function ApproveClient(arg1) {
  return window['go']['main']['App']['ApproveClient'](arg1);
}

export function DisconnectAll() {
  return window['go']['main']['App']['DisconnectAll']();
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetDisplays() {
  return window['go']['main']['App']['GetDisplays']();
}

export function GetSharingStatus() {
  return window['go']['main']['App']['GetSharingStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OnClientStateChanged() {
  return window['go']['main']['App']['OnClientStateChanged']();
}

export function RejectClient(arg1) {
  return window['go']['main']['App']['RejectClient'](arg1);
}

export function SelectDisplay(arg1) {
  return window['go']['main']['App']['SelectDisplay'](arg1);
}

export function SendAnnouncement(arg1) {
  return window['go']['main']['App']['SendAnnouncement'](arg1);
}

export function StartSharing(arg1) {
  return window['go']['main']['App']['StartSharing'](arg1);
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}
