// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {main} from '../models';
import {capture} from '../models';

export function ApproveAll():Promise<void>;

export function ApproveClient(arg1:string):Promise<void>;

export function CheckScreenCapturePermission():Promise<boolean>;

export function ClearChatHistory():Promise<void>;

export function DisconnectAll():Promise<void>;

export function DisconnectClient(arg1:string):Promise<void>;

export function GetChatMessages():Promise<Array<server.ChatMessage>>;

export function GetClients():Promise<main.ClientsPayload>;

export function GetDisplays():Promise<Array<main.DisplayInfo>>;

export function GetQualityPresets():Promise<Array<capture.QualityPreset>>;

export function GetSharingStatus():Promise<boolean>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function IsScreenPaused():Promise<boolean>;

export function IsScreenStreaming():Promise<boolean>;

export function OnClientStateChanged():Promise<void>;

export function OpenScreenCaptureSettings():Promise<void>;

export function PauseScreenShare():Promise<void>;

export function RejectClient(arg1:string):Promise<void>;

export function RequestScreenCapturePermission():Promise<boolean>;

export function ResumeScreenShare():Promise<void>;

export function SelectDisplay(arg1:string):Promise<void>;

export function SendAnnouncement(arg1:string):Promise<void>;

export function SendChatMessage(arg1:string):Promise<void>;

export function SendCodeSnippet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetQualityPreset(arg1:string):Promise<void>;

export function StartSharing(arg1:number):Promise<boolean>;

export function StopSharing():Promise<void>;
