// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApproveAll():Promise<void>;

export function ApproveClient(arg1:string):Promise<void>;

export function DisconnectAll():Promise<void>;

export function DisconnectClient(arg1:string):Promise<void>;

export function GetClients():Promise<main.ClientsPayload>;

export function GetDisplays():Promise<Array<main.DisplayInfo>>;

export function GetSharingStatus():Promise<boolean>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function OnClientStateChanged():Promise<void>;

export function RejectClient(arg1:string):Promise<void>;

export function SelectDisplay(arg1:string):Promise<void>;

export function SendAnnouncement(arg1:string):Promise<void>;

export function StartSharing(arg1:number):Promise<boolean>;

export function StopSharing():Promise<void>;
