// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveAll() {
  return window['go']['main']['App']['ApproveAll']();
}

export function ApproveClient(arg1) {
  return window['go']['main']['App']['ApproveClient'](arg1);
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function DisconnectAll() {
  return window['go']['main']['App']['DisconnectAll']();
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function GetChatMessages() {
  return window['go']['main']['App']['GetChatMessages']();
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetDisplays() {
  return window['go']['main']['App']['GetDisplays']();
}

export function GetQualityPresets() {
  return window['go']['main']['App']['GetQualityPresets']();
}

export function GetSharingStatus() {
  return window['go']['main']['App']['GetSharingStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function IsAutoApprove() {
  return window['go']['main']['App']['IsAutoApprove']();
}

export function IsScreenPaused() {
  return window['go']['main']['App']['IsScreenPaused']();
}

export function IsScreenStreaming() {
  return window['go']['main']['App']['IsScreenStreaming']();
}

export function OnClientStateChanged() {
  return window['go']['main']['App']['OnClientStateChanged']();
}

export function PauseScreenShare() {
  return window['go']['main']['App']['PauseScreenShare']();
}

export function RejectClient(arg1) {
  return window['go']['main']['App']['RejectClient'](arg1);
}

export function ResumeScreenShare() {
  return window['go']['main']['App']['ResumeScreenShare']();
}

export function SelectDisplay(arg1) {
  return window['go']['main']['App']['SelectDisplay'](arg1);
}

export function SendAnnouncement(arg1) {
  return window['go']['main']['App']['SendAnnouncement'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SendCodeSnippet(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCodeSnippet'](arg1, arg2, arg3);
}

export function SetAutoApprove(arg1) {
  return window['go']['main']['App']['SetAutoApprove'](arg1);
}

export function SetQualityPreset(arg1) {
  return window['go']['main']['App']['SetQualityPreset'](arg1);
}

export function StartSharing(arg1) {
  return window['go']['main']['App']['StartSharing'](arg1);
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}
